# Ok Winddows
# Estagio 1 - Será responsavel em construir nossa aplicação
FROM node:10.9.0-alpine as nodealpine
WORKDIR /app
COPY package.json /app/
RUN npm i npm@6.2.0 -g
#RUN npm install
COPY ./ /app/
ARG env=prod
RUN npm run build

# Estagio 2 - Será responsavel por expor a aplicação
FROM  nginx:1.13.12-alpine
COPY --from=nodealpine /app/dist/Angular607 /usr/share/nginx/html
COPY ./nginx-custom.conf /etc/nginx/conf.d/default.conf